### ISSUE TITLE
Python 2.7 Compability

### ISSUE THREAD

**Issue by sparkheo7** [MrPowers/chispa#7]
Dear team,

I am trying to integrate this library in my build process for unit test and got below-mentioned error during the build process. We are in the python 2.7 environments. Can you please help here. 

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/myproject/build/venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/var/lib/jenkins/workspace/myproject/build/venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/var/lib/jenkins/workspace/myproject/build/venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/lib/jenkins/workspace/myproject/test/test_functions.py", line 3, in <module>
    from chispa import *
  File "/var/lib/jenkins/workspace/myproject/build/venv/lib/python2.7/site-packages/chispa/__init__.py", line 1, in <module>
    from .dataframe_comparer import DataFramesNotEqualError, assert_df_equality, assert_approx_df_equality
  File "/var/lib/jenkins/workspace/myproject/build/venv/lib/python2.7/site-packages/chispa/dataframe_comparer.py", line 2, in <module>
    from chispa.bcolors import *
  File "/var/lib/jenkins/workspace/myproject/build/venv/lib/python2.7/site-packages/chispa/bcolors.py", line 28
    def blue(s: str) -> str:

**Comment by sparkheo7** [comment]
I believe this happening because type annotations are not supported in python 2.7.

**Comment by MrPowers** [comment]
Thanks for opening this issue.  Python 2 is EOL and will not be supported, sorry about that!
